name: Wasm-pack on tag push

on:
  push:
    tags:
      - '*'

env:
  TAG_NAME: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: create env file
        run: |
          touch .env
          echo SM4_SDK_KEY=${{ secrets.SM4_SDK_KEY }} >> .env
          echo SM4_SDK_IV=${{ secrets.SM4_SDK_IV }} >> .env

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'

      - name: Build with wasm-pack
        run: wasm-pack build --target web --out-dir pkg --out-name sm4_sdk --release

      - name: Compress pkg directory
        run: |
          zip -r pkg-${{ env.TAG_NAME }}.zip pkg

      - name: Upload artifact to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.SM4_SDK_TOKEN }}
          files: pkg-${{ env.TAG_NAME }}.zip
