name: Wasm-pack on tag push

on:
  push:
    tags:
      - '*'

env:
  TAG_NAME: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SM4_SDK_KEY: ${{ secrets.SM4_SDK_KEY }}
      SM4_SDK_IV: ${{ secrets.SM4_SDK_IV }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'

      - name: Build with wasm-pack
        run: wasm-pack build --target web --out-dir pkg --out-name sm4_sdk --release

      - name: Compress pkg directory
        run: |
          zip -r pkg.zip pkg

      - name: Upload artifact to GitHub Releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SM4_SDK_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: pkg.zip
          asset_name: pkg-${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip
